{
  "wrapper": "plaintext",
  "text": "Ok finally able to run the job fine ...the culprit was an older version of aws inside flink\nkinesis connector jar , also rebuilt flink again from source with maven 3.25 ,I was on 3.3*\nand it had weird transitive dependency problems.\n\n\n\n\nOn Apr 15, 2017, at 11:13 AM, Sathi Chowdhury <Sathi.Chowdhury@elliemae.com<mailto:Sathi.Chowdhury@elliemae.com>>\nwrote:\n\nI have redone the pipeline with flink-1.3-SNAPSHOT and running on EMR 5.4, the aws-sdk-java\nlatest libraries directly in flink lib dir.\nI have come to the point where I get the java.net.SocketException: Broken pipe (Write failed).\nEager to get a reply and a clue on this!\n\njava.io.IOException: Error sending data back to client (ip-172-31-42-238/172.31.42.238:42753)\n        at org.apache.flink.contrib.streaming.CollectSink.invoke(CollectSink.java:64)\n        at org.apache.flink.streaming.api.operators.StreamSink.processElement(StreamSink.java:38)\n        at org.apache.flink.streaming.runtime.io.StreamInputProcessor.processInput(StreamInputProcessor.java:208)\n        at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask.run(OneInputStreamTask.java:66)\n        at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:261)\n        at org.apache.flink.runtime.taskmanager.Task.run(Task.java:679)\n        at java.lang.Thread.run(Thread.java:745)\nCaused by: com.esotericsoftware.kryo.KryoException: java.net.SocketException: Broken pipe\n(Write failed)\n        at com.esotericsoftware.kryo.io.Output.flush(Output.java:165)\n        at com.esotericsoftware.kryo.io.Output.require(Output.java:142)\n        at com.esotericsoftware.kryo.io.Output.writeString_slow(Output.java:444)\n        at com.esotericsoftware.kryo.io.Output.writeString(Output.java:345)\n        at com.esotericsoftware.kryo.serializers.DefaultSerializers$StringSerializer.write(DefaultSerializers.java:173)\n        at com.esotericsoftware.kryo.serializers.DefaultSerializers$StringSerializer.write(DefaultSerializers.java:166)\n        at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:599)\n        at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:95)\n        at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:21)\n        at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:599)\n        at org.apache.flink.api.java.typeutils.runtime.kryo.KryoSerializer.serialize(KryoSerializer.java:202)\n        at org.apache.flink.contrib.streaming.CollectSink.invoke(CollectSink.java:61)\n        ... 6 more\nCaused by: java.net.SocketException: Broken pipe (Write failed)\n        at java.net.SocketOutputStream.socketWrite0(Native Method)\n        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)\n        at java.net.SocketOutputStream.write(SocketOutputStream.java:155)\n        at java.io.DataOutputStream.write(DataOutputStream.java:107)\n        at org.apache.flink.api.java.typeutils.runtime.DataOutputViewStream.write(DataOutputViewStream.java:41)\n        at com.esotericsoftware.kryo.io.Output.flush(Output.java:163)\n        ... 17 more\nThanks\n\n\nFrom: Sathi Chowdhury <Sathi.Chowdhury@elliemae.com<mailto:Sathi.Chowdhury@elliemae.com>>\nDate: Friday, April 14, 2017 at 1:29 AM\nTo: \"user@flink.apache.org<mailto:user@flink.apache.org>\" <user@flink.apache.org<mailto:user@flink.apache.org>>\nSubject: Re: Flink errors out and job fails--IOException from CollectSink.open()\n\nI am consistently seeing the same behavior\u00e2\u20ac\u00a6tried with elevated memory for job manager and\ntaskmanager\ntaskmanager.rpc.port: 6123\ntaskmanager.data.port: 4964\ntaskmanager.heap.mb: 39000\ntaskmanager.numberOfTaskSlots: 1\ntaskmanager.network.numberOfBuffers: 16368\ntaskmanager.memory.preallocate: false\nparallelization.degree.default: 4\neven though the jobmanager is  restarting the flink job ,but the subtasks once reach to cancelled\nstate does not revive\nI have no clue how to approach this.\nThanks\n\n\nFrom: Sathi Chowdhury <Sathi.Chowdhury@elliemae.com<mailto:Sathi.Chowdhury@elliemae.com>>\nDate: Thursday, April 13, 2017 at 9:52 PM\nTo: Ted Yu <yuzhihong@gmail.com<mailto:yuzhihong@gmail.com>>, \"user@flink.apache.org<mailto:user@flink.apache.org>\"\n<user@flink.apache.org<mailto:user@flink.apache.org>>\nSubject: Re: Flink errors out and job fails--IOException from CollectSink.open()\n\nIn my jobmanager log I see this exception , probably is the root cause why the whole job is\nkilled\u00e2\u20ac\u00a6is there any memory problem in jobmanager ? any clue for this error below?\nI ran the yarn-session\n\n\nAnd my flink-conf.yaml is pretty much unmodified\njobmanager.heap.mb: 256\n\ntaskmanager.heap.mb: 512\n\ntaskmanager.numberOfTaskSlots: 2\n\ntaskmanager.memory.preallocate: false\n\nparallelism.default: 1\n\ninvoke of yarn-session.sh\nHADOOP_CONF_DIR=/etc/hadoop/conf $FLINK_HOME/bin/yarn-session.sh -d -n 2 -s 1 -tm 2048\n\nThanks\nThe error in job manager is as below\n\n2017-04-14 04:26:33,570 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph     \n  - Co-Flat Map -> Sink: Unnamed (1/1) (0c515e082713970381dcd34da87cfcf4) switched from\nRUNNING to FAILED.\njava.lang.RuntimeException: Could not forward element to next operator\n        at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:425)\n        at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:407)\n        at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:797)\n        at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:775)\n        at org.apache.flink.streaming.api.operators.TimestampedCollector.collect(TimestampedCollector.java:51)\n        at com.elliemae.stream.StreamerImpl$StreamerCoFlatMapFunction.flatMap2(StreamerImpl.java:253)\n        at com.elliemae.stream.StreamerImpl$StreamerCoFlatMapFunction.flatMap2(StreamerImpl.java:234)\n        at org.apache.flink.streaming.api.operators.co.CoStreamFlatMap.processElement2(CoStreamFlatMap.java:56)\n        at org.apache.flink.streaming.runtime.io.StreamTwoInputProcessor.processInput(StreamTwoInputProcessor.java:213)\n        at org.apache.flink.streaming.runtime.tasks.TwoInputStreamTask.run(TwoInputStreamTask.java:87)\n        at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:272)\n        at org.apache.flink.runtime.taskmanager.Task.run(Task.java:655)\n        at java.lang.Thread.run(Thread.java:745)\nCaused by: java.io.IOException: Error sending data back to client (ip-172-31-31-172/172.31.31.172:46147)\n        at org.apache.flink.contrib.streaming.CollectSink.invoke(CollectSink.java:64)\n        at org.apache.flink.streaming.api.operators.StreamSink.processElement(StreamSink.java:38)\n        at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:422)\n        ... 12 more\nCaused by: com.esotericsoftware.kryo.KryoException: java.net.SocketException: Connection reset\n        at com.esotericsoftware.kryo.io.Output.flush(Output.java:165)\n        at com.esotericsoftware.kryo.io.Output.require(Output.java:142)\n        at com.esotericsoftware.kryo.io.Output.writeString_slow(Output.java:444)\n        at com.esotericsoftware.kryo.io.Output.writeString(Output.java:345)\n        at com.esotericsoftware.kryo.serializers.DefaultSerializers$StringSerializer.write(DefaultSerializers.java:173)\n        at com.esotericsoftware.kryo.serializers.DefaultSerializers$StringSerializer.write(DefaultSerializers.java:166)\n        at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:599)\n        at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:95)\n        at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:21)\n        at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:599)\n        at org.apache.flink.api.java.typeutils.runtime.kryo.KryoSerializer.serialize(KryoSerializer.java:203)\n        at org.apache.flink.contrib.streaming.CollectSink.invoke(CollectSink.java:61)\n        ... 14 more\nCaused by: java.net.SocketException: Connection reset\n        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:115)\n        at java.net.SocketOutputStream.write(SocketOutputStream.java:155)\n        at java.io.DataOutputStream.write(DataOutputStream.java:107)\n        at org.apache.flink.api.java.typeutils.runtime.DataOutputViewStream.write(DataOutputViewStream.java:39)\n        at com.esotericsoftware.kryo.io.Output.flush(Output.java:163)\n        ... 25 more\n2017-04-14 04:26:33,572 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph     \n  - Job Flink Streaming Job (6c9267453a74d0ef58e678351ac0b49c) switched from state RUNNING\nto FAILING.\n2017-04-14 04:49:10,707 WARN  akka.remote.ReliableDeliverySupervisor                     \n  - Association with remote system [akka.tcp://flink@ip-172-31-31-172.us-west-2.compute.internal:37737]\nhas failed, address is now gated for [5000] ms. Reason: [Association failed with [akka.tcp://flink@ip-172-31-31-172.us-west-2.compute.internal:37737]]\nCaused by: [Connection refused: ip-172-31-31-172.us<http://ip-172-31-31-172.us>-west-2.compute.internal/172.31.31.172:37737]\n2017-04-14 04:49:10,712 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph     \n  - Source: Custom Source (1/1) (b9af6dd459e576a669a12b08a830c24e) switched from DEPLOYING\nto RUNNING.\n2017-04-14 04:49:10,713 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph     \n  - Source: Custom Source (1/1) (c5fe4b6df26e03f4c2604ec89a92ad8f) switched from DEPLOYING\nto RUNNING.\n2017-04-14 04:49:10,715 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph     \n  - Source: Custom Source (1/1) (7f614d51527252cbb9ffcfc0d660fe4e) switched from DEPLOYING\nto RUNNING.\n2017-04-14 04:49:10,717 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph     \n  - Co-Flat Map (1/1) (cd1f1ecf9408b4ac58bea6be99e5c89a) switched from DEPLOYING to RUNNING.\n2017-04-14 04:49:10,718 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph     \n  - Co-Flat Map -> Sink: Unnamed (1/1) (82713fda323b6325815b1b228a3d93f8) switched from\nDEPLOYING to RUNNING.\n2017-04-14 04:49:10,740 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph     \n  - Co-Flat Map -> Sink: Unnamed (1/1) (82713fda323b6325815b1b228a3d93f8) switched from\nRUNNING to FAILED.\njava.io.IOException: Cannot connect to the client to send back the stream\n        at org.apache.flink.contrib.streaming.CollectSink.open(CollectSink.java:80)\n        at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:36)\n        at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:112)\n        at org.apache.flink.streaming.runtime.tasks.StreamTask.openAllOperators(StreamTask.java:386)\n        at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:262)\n        at org.apache.flink.runtime.taskmanager.Task.run(Task.java:655)\n        at java.lang.Thread.run(Thread.java:745)\nCaused by: java.net.ConnectException: Connection refused (Connection refused)\n        at java.net.PlainSocketImpl.socketConnect(Native Method)\n        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)\n        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)\n        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)\n        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)\n        at java.net.Socket.connect(Socket.java:589)\n        at java.net.Socket.connect(Socket.java:538)\n        at java.net.Socket.<init>(Socket.java:434)\n        at java.net.Socket.<init>(Socket.java:244)\n        at org.apache.flink.contrib.streaming.CollectSink.open(CollectSink.java:75)\n        ... 6 more\n\n\nFrom: Ted Yu <yuzhihong@gmail.com<mailto:yuzhihong@gmail.com>>\nDate: Thursday, April 13, 2017 at 6:01 PM\nTo: Sathi Chowdhury <Sathi.Chowdhury@elliemae.com<mailto:Sathi.Chowdhury@elliemae.com>>\nCc: \"user@flink.apache.org<mailto:user@flink.apache.org>\" <user@flink.apache.org<mailto:user@flink.apache.org>>\nSubject: Re: Flink errors out and job fails--IOException from CollectSink.open()\n\nHere is the line where NPE was thrown:\n\n    mainThread.interrupt(); // the main thread may be sleeping for the discovery interval\n\nI wonder if runFetcher() encountered running being false - otherwise mainThread should not\nhave been null.\n\nLooks like we should check whether mainThread is null when shutting down.\n\nOn Thu, Apr 13, 2017 at 5:46 PM, Sathi Chowdhury <Sathi.Chowdhury@elliemae.com<mailto:Sathi.Chowdhury@elliemae.com>>\nwrote:\nThe taskmanger log does not point a line in my code ..but it seems like the error occurs while\nit is trying to fetch kinesis record inside connector jar\n\nred sequence number 49572261908151269541343187919820576263466496304458235906\n2017-04-13 23:28:23,470 INFO  org.apache.flink.streaming.connectors.kinesis.FlinkKinesisConsumer\n - Subtask 0 is seeding the fetcher with restored shard KinesisStreamShard{streamName='dev-ingest-kinesis-us-west-2',\nshard='{ShardId: shardId-000000000009,HashKeyRange: {StartingHashKey: 306254130228844617117037146688591390310,EndingHashKey:\n340282366920938463463374607431768211455},SequenceNumberRange: {StartingSequenceNumber: 49572254078827945986407789245674345090539511066904232082,}}'},\nstarting state set to the restored sequence number LATEST_SEQUENCE_NUM\n2017-04-13 23:28:23,471 WARN  org.apache.flink.streaming.connectors.kinesis.FlinkKinesisConsumer\n - Error while closing Kinesis data fetcher\njava.lang.NullPointerException\n        at org.apache.flink.streaming.connectors.kinesis.internals.KinesisDataFetcher.shutdownFetcher(KinesisDataFetcher.java:472)\n        at org.apache.flink.streaming.connectors.kinesis.FlinkKinesisConsumer.cancel(FlinkKinesisConsumer.java:246)\n        at org.apache.flink.streaming.connectors.kinesis.FlinkKinesisConsumer.close(FlinkKinesisConsumer.java:256)\n        at org.apache.flink.api.common.functions.util.FunctionUtils.closeFunction(FunctionUtils.java:43)\n        at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.dispose(AbstractUdfStreamOperator.java:127)\n        at org.apache.flink.streaming.runtime.tasks.StreamTask.disposeAllOperators(StreamTask.java:442)\n        at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:343)\n        at org.apache.flink.runtime.taskmanager.Task.run(Task.java:655)\n        at java.lang.Thread.run(Thread.java:745)\n2017-04-13 23:28:23,471 WARN  org.apache.flink.streaming.connectors.kinesis.FlinkKinesisConsumer\n - Error while closing Kinesis data fetcher\njava.lang.NullPointerException\n        at org.apache.flink.streaming.connectors.kinesis.internals.KinesisDataFetcher.shutdownFetcher(KinesisDataFetcher.java:472)\n        at org.apache.flink.streaming.connectors.kinesis.FlinkKinesisConsumer.cancel(FlinkKinesisConsumer.java:246)\n        at org.apache.flink.streaming.connectors.kinesis.FlinkKinesisConsumer.close(FlinkKinesisConsumer.java:256)\n        at org.apache.flink.api.common.functions.util.FunctionUtils.closeFunction(FunctionUtils.java:43)\n        at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.dispose(AbstractUdfStreamOperator.java:127)\n        at org.apache.flink.streaming.runtime.tasks.StreamTask.disposeAllOperators(StreamTask.java:442)\n        at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:343)\n        at org.apache.flink.runtime.taskmanager.Task.run(Task.java:655)\n        at java.lang.Thread.run(Thread.java:745)\n2017-04-13 23:28:23,472 INFO  org.apache.flink.runtime.taskmanager.Task                  \n  - Source: Custom Source (1/1) (8a7301a437cb2d052208ee42c994104b) switched from CANCELING\nto CANCELED.\n2017-04-13 23:28:23,471 INFO  org.apache.flink.streaming.connectors.kinesis.FlinkKinesisConsumer\n - Subtask 0 is seeding the fetcher with restored shard KinesisStreamShard{streamName='dev-ingest-kinesis-us-west-2',\nshard='{ShardId: shardId-000000000006,HashKeyRange: {StartingHashKey: 204169420152563078078024764459060926873,EndingHashKey:\n238197656844656924424362225202237748018},SequenceNumberRange: {StartingSequenceNumber: 49572254078761043750812197376249737935721565982386290786,}}'},\nstarting state set to the restored sequence number LATEST_SEQUENCE_NUM\n2017-04-13 23:28:23,472 INFO  org.apache.flink.runtime.taskmanager.Task                  \n  - Freeing task resources for Source: Custom Source (1/1) (8a7301a437cb2d052208ee42c994104b).\n\n\nFrom: Sathi Chowdhury <Sathi.Chowdhury@elliemae.com<mailto:Sathi.Chowdhury@elliemae.com>>\nDate: Thursday, April 13, 2017 at 5:44 PM\nTo: Ted Yu <yuzhihong@gmail.com<mailto:yuzhihong@gmail.com>>\n\nCc: \"user@flink.apache.org<mailto:user@flink.apache.org>\" <user@flink.apache.org<mailto:user@flink.apache.org>>\nSubject: Re: Flink errors out and job fails--IOException from CollectSink.open()\n\nHi Ted, Sorry for my big font earlier\u00e2\u20ac\u00a6was not intended \u00e2\u02dc\u00ba\n\nI am on flink 1.2.0\nI built flink-connector-kinesis_2.10-1.2.0.jar from source and included in the fatjar I am\nrunning.\nFollowed this http://www.kidder.io/2017/02/15/flink-kinesis-streaming-connector/<https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.kidder.io%2F2017%2F02%2F15%2Fflink-kinesis-streaming-connector%2F&data=01%7C01%7C%7Cfc97be832d1a4062d75608d482cf675f%7C0d009d13c2cd47d891dd2ae838b00d4b%7C0&sdata=avPl4%2FU5DTjZW09Zby9CeUttUNpiGWH%2Bvnycy9PhUDA%3D&reserved=0>\n\n\nFrom code I read a kinesis stream using\n\nconsumerConfig.setProperty(ConsumerConfigConstants.AWS_REGION, region);\nconsumerConfig.setProperty(ConsumerConfigConstants.DEFAULT_STREAM_INITIAL_POSITION, \"LATEST\");\nconsumerConfig.setProperty(ConsumerConfigConstants.AWS_CREDENTIALS_PROVIDER, \"AUTO\");\nconsumerConfig.setProperty(ConsumerConfigConstants.SHARD_GETRECORDS_MAX, \"10\");\nconsumerConfig.setProperty(ConsumerConfigConstants.SHARD_GETRECORDS_RETRIES, \"200\");\nconsumerConfig.setProperty(ConsumerConfigConstants.SHARD_GETRECORDS_INTERVAL_MILLIS, \"2000\");\nDataStream<Map<String, Object>> stream = env.addSource(new FlinkKinesisConsumer<>(inputStream,\nnew MyJsonDeserializationSchema(), consumerConfig));\n\n\nWhile I push the json event to the Kinesis stream intermittently I see this NPE and flink\njob fails\n\n\n2017-04-14 00:31:54,672 WARN  org.apache.flink.streaming.connectors.kinesis.FlinkKinesisConsumer\n - Error while closing Kinesis data fetcher\n\njava.lang.NullPointerException\n\n               at org.apache.flink.streaming.connectors.kinesis.internals.KinesisDataFetcher.shutdownFetcher(KinesisDataFetcher.java:472)\n\n               at org.apache.flink.streaming.connectors.kinesis.FlinkKinesisConsumer.cancel(FlinkKinesisConsumer.java:246)\n\n               at org.apache.flink.streaming.connectors.kinesis.FlinkKinesisConsumer.close(FlinkKinesisConsumer.java:256)\n\n               at org.apache.flink.api.common.functions.util.FunctionUtils.closeFunction(FunctionUtils.java:43)\n\n               at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.dispose(AbstractUdfStreamOperator.java:127)\n\n               at org.apache.flink.streaming.runtime.tasks.StreamTask.disposeAllOperators(StreamTask.java:442)\n\n               at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:343)\n\n               at org.apache.flink.runtime.taskmanager.Task.run(Task.java:655)\n\n               at java.lang.Thread.run(Thread.java:745)\n\nThanks\nSathi\n\n\n\nFrom: Ted Yu <yuzhihong@gmail.com<mailto:yuzhihong@gmail.com>>\nDate: Thursday, April 13, 2017 at 5:02 PM\nTo: Sathi Chowdhury <Sathi.Chowdhury@elliemae.com<mailto:Sathi.Chowdhury@elliemae.com>>\nCc: \"user@flink.apache.org<mailto:user@flink.apache.org>\" <user@flink.apache.org<mailto:user@flink.apache.org>>\nSubject: Re: Flink errors out and job fails--IOException from CollectSink.open()\n\nCan you give us a bit more information ?\n\nrelease of flink\nsnippet of your code\n\nThanks\n=============Notice to Recipient: This e-mail transmission, and any documents, files or previous\ne-mail messages attached to it may contain information that is confidential or legally privileged,\nand intended for the use of the individual or entity named above. If you are not the intended\nrecipient, or a person responsible for delivering it to the intended recipient, you are hereby\nnotified that you must not read this transmission and that any disclosure, copying, printing,\ndistribution or use of any of the information contained in or attached to this transmission\nis STRICTLY PROHIBITED. If you have received this transmission in error, please immediately\nnotify the sender by telephone or return e-mail and delete the original transmission and its\nattachments without reading or saving in any manner. Thank you. =============\n=============Notice to Recipient: This e-mail transmission, and any documents, files or previous\ne-mail messages attached to it may contain information that is confidential or legally privileged,\nand intended for the use of the individual or entity named above. If you are not the intended\nrecipient, or a person responsible for delivering it to the intended recipient, you are hereby\nnotified that you must not read this transmission and that any disclosure, copying, printing,\ndistribution or use of any of the information contained in or attached to this transmission\nis STRICTLY PROHIBITED. If you have received this transmission in error, please immediately\nnotify the sender by telephone or return e-mail and delete the original transmission and its\nattachments without reading or saving in any manner. Thank you. =============\n\n=============Notice to Recipient: This e-mail transmission, and any documents, files or previous\ne-mail messages attached to it may contain information that is confidential or legally privileged,\nand intended for the use of the individual or entity named above. If you are not the intended\nrecipient, or a person responsible for delivering it to the intended recipient, you are hereby\nnotified that you must not read this transmission and that any disclosure, copying, printing,\ndistribution or use of any of the information contained in or attached to this transmission\nis STRICTLY PROHIBITED. If you have received this transmission in error, please immediately\nnotify the sender by telephone or return e-mail and delete the original transmission and its\nattachments without reading or saving in any manner. Thank you. =============\n=============Notice to Recipient: This e-mail transmission, and any documents, files or previous\ne-mail messages attached to it may contain information that is confidential or legally privileged,\nand intended for the use of the individual or entity named above. If you are not the intended\nrecipient, or a person responsible for delivering it to the intended recipient, you are hereby\nnotified that you must not read this transmission and that any disclosure, copying, printing,\ndistribution or use of any of the information contained in or attached to this transmission\nis STRICTLY PROHIBITED. If you have received this transmission in error, please immediately\nnotify the sender by telephone or return e-mail and delete the original transmission and its\nattachments without reading or saving in any manner. Thank you. =============\n=============Notice to Recipient: This e-mail transmission, and any documents, files or previous\ne-mail messages attached to it may contain information that is confidential or legally privileged,\nand intended for the use of the individual or entity named above. If you are not the intended\nrecipient, or a person responsible for delivering it to the intended recipient, you are hereby\nnotified that you must not read this transmission and that any disclosure, copying, printing,\ndistribution or use of any of the information contained in or attached to this transmission\nis STRICTLY PROHIBITED. If you have received this transmission in error, please immediately\nnotify the sender by telephone or return e-mail and delete the original transmission and its\nattachments without reading or saving in any manner. Thank you. =============\n=============Notice to Recipient: This e-mail transmission, and any documents, files or previous\ne-mail messages attached to it may contain information that is confidential or legally privileged,\nand intended for the use of the individual or entity named above. If you are not the intended\nrecipient, or a person responsible for delivering it to the intended recipient, you are hereby\nnotified that you must not read this transmission and that any disclosure, copying, printing,\ndistribution or use of any of the information contained in or attached to this transmission\nis STRICTLY PROHIBITED. If you have received this transmission in error, please immediately\nnotify the sender by telephone or return e-mail and delete the original transmission and its\nattachments without reading or saving in any manner. Thank you. =============\n",
  "denotations": [
    {
      "id": 1,
      "start": 0,
      "end": 237,
      "text": "Ok finally able to run the job fine ...the culprit was an older version of aws inside flink\nkinesis connector jar , also rebuilt flink again from source with maven 3.25 ,I was on 3.3*\nand it had weird transitive dependency problems.\n\n\n\n\n",
      "type": "Body",
      "meta": null
    },
    {
      "id": 2,
      "start": 237,
      "end": 358,
      "text": "On Apr 15, 2017, at 11:13 AM, Sathi Chowdhury <Sathi.Chowdhury@elliemae.com<mailto:Sathi.Chowdhury@elliemae.com>>\nwrote:\n",
      "type": "Header",
      "meta": null
    },
    {
      "id": 3,
      "start": 19920,
      "end": 25014,
      "text": "\nCan you give us a bit more information ?\n\nrelease of flink\nsnippet of your code\n\nThanks\n=============Notice to Recipient: This e-mail transmission, and any documents, files or previous\ne-mail messages attached to it may contain information that is confidential or legally privileged,\nand intended for the use of the individual or entity named above. If you are not the intended\nrecipient, or a person responsible for delivering it to the intended recipient, you are hereby\nnotified that you must not read this transmission and that any disclosure, copying, printing,\ndistribution or use of any of the information contained in or attached to this transmission\nis STRICTLY PROHIBITED. If you have received this transmission in error, please immediately\nnotify the sender by telephone or return e-mail and delete the original transmission and its\nattachments without reading or saving in any manner. Thank you. =============\n=============Notice to Recipient: This e-mail transmission, and any documents, files or previous\ne-mail messages attached to it may contain information that is confidential or legally privileged,\nand intended for the use of the individual or entity named above. If you are not the intended\nrecipient, or a person responsible for delivering it to the intended recipient, you are hereby\nnotified that you must not read this transmission and that any disclosure, copying, printing,\ndistribution or use of any of the information contained in or attached to this transmission\nis STRICTLY PROHIBITED. If you have received this transmission in error, please immediately\nnotify the sender by telephone or return e-mail and delete the original transmission and its\nattachments without reading or saving in any manner. Thank you. =============\n\n=============Notice to Recipient: This e-mail transmission, and any documents, files or previous\ne-mail messages attached to it may contain information that is confidential or legally privileged,\nand intended for the use of the individual or entity named above. If you are not the intended\nrecipient, or a person responsible for delivering it to the intended recipient, you are hereby\nnotified that you must not read this transmission and that any disclosure, copying, printing,\ndistribution or use of any of the information contained in or attached to this transmission\nis STRICTLY PROHIBITED. If you have received this transmission in error, please immediately\nnotify the sender by telephone or return e-mail and delete the original transmission and its\nattachments without reading or saving in any manner. Thank you. =============\n=============Notice to Recipient: This e-mail transmission, and any documents, files or previous\ne-mail messages attached to it may contain information that is confidential or legally privileged,\nand intended for the use of the individual or entity named above. If you are not the intended\nrecipient, or a person responsible for delivering it to the intended recipient, you are hereby\nnotified that you must not read this transmission and that any disclosure, copying, printing,\ndistribution or use of any of the information contained in or attached to this transmission\nis STRICTLY PROHIBITED. If you have received this transmission in error, please immediately\nnotify the sender by telephone or return e-mail and delete the original transmission and its\nattachments without reading or saving in any manner. Thank you. =============\n=============Notice to Recipient: This e-mail transmission, and any documents, files or previous\ne-mail messages attached to it may contain information that is confidential or legally privileged,\nand intended for the use of the individual or entity named above. If you are not the intended\nrecipient, or a person responsible for delivering it to the intended recipient, you are hereby\nnotified that you must not read this transmission and that any disclosure, copying, printing,\ndistribution or use of any of the information contained in or attached to this transmission\nis STRICTLY PROHIBITED. If you have received this transmission in error, please immediately\nnotify the sender by telephone or return e-mail and delete the original transmission and its\nattachments without reading or saving in any manner. Thank you. =============\n=============Notice to Recipient: This e-mail transmission, and any documents, files or previous\ne-mail messages attached to it may contain information that is confidential or legally privileged,\nand intended for the use of the individual or entity named above. If you are not the intended\nrecipient, or a person responsible for delivering it to the intended recipient, you are hereby\nnotified that you must not read this transmission and that any disclosure, copying, printing,\ndistribution or use of any of the information contained in or attached to this transmission\nis STRICTLY PROHIBITED. If you have received this transmission in error, please immediately\nnotify the sender by telephone or return e-mail and delete the original transmission and its\nattachments without reading or saving in any manner. Thank you. =============\n",
      "type": "Body",
      "meta": null
    },
    {
      "id": 4,
      "start": 20001,
      "end": 20009,
      "text": "\nThanks\n",
      "type": "Body/Outro",
      "meta": null
    },
    {
      "id": 5,
      "start": 19534,
      "end": 19920,
      "text": "From: Ted Yu <yuzhihong@gmail.com<mailto:yuzhihong@gmail.com>>\nDate: Thursday, April 13, 2017 at 5:02 PM\nTo: Sathi Chowdhury <Sathi.Chowdhury@elliemae.com<mailto:Sathi.Chowdhury@elliemae.com>>\nCc: \"user@flink.apache.org<mailto:user@flink.apache.org>\" <user@flink.apache.org<mailto:user@flink.apache.org>>\nSubject: Re: Flink errors out and job fails--IOException from CollectSink.open()\n",
      "type": "Header",
      "meta": null
    },
    {
      "id": 6,
      "start": 19517,
      "end": 19531,
      "text": "\nThanks\nSathi\n",
      "type": "Body/Outro",
      "meta": null
    },
    {
      "id": 7,
      "start": 17003,
      "end": 19534,
      "text": "\nHi Ted, Sorry for my big font earlier\u00e2\u20ac\u00a6was not intended \u00e2\u02dc\u00ba\n\nI am on flink 1.2.0\nI built flink-connector-kinesis_2.10-1.2.0.jar from source and included in the fatjar I am\nrunning.\nFollowed this http://www.kidder.io/2017/02/15/flink-kinesis-streaming-connector/<https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.kidder.io%2F2017%2F02%2F15%2Fflink-kinesis-streaming-connector%2F&data=01%7C01%7C%7Cfc97be832d1a4062d75608d482cf675f%7C0d009d13c2cd47d891dd2ae838b00d4b%7C0&sdata=avPl4%2FU5DTjZW09Zby9CeUttUNpiGWH%2Bvnycy9PhUDA%3D&reserved=0>\n\n\nFrom code I read a kinesis stream using\n\nconsumerConfig.setProperty(ConsumerConfigConstants.AWS_REGION, region);\nconsumerConfig.setProperty(ConsumerConfigConstants.DEFAULT_STREAM_INITIAL_POSITION, \"LATEST\");\nconsumerConfig.setProperty(ConsumerConfigConstants.AWS_CREDENTIALS_PROVIDER, \"AUTO\");\nconsumerConfig.setProperty(ConsumerConfigConstants.SHARD_GETRECORDS_MAX, \"10\");\nconsumerConfig.setProperty(ConsumerConfigConstants.SHARD_GETRECORDS_RETRIES, \"200\");\nconsumerConfig.setProperty(ConsumerConfigConstants.SHARD_GETRECORDS_INTERVAL_MILLIS, \"2000\");\nDataStream<Map<String, Object>> stream = env.addSource(new FlinkKinesisConsumer<>(inputStream,\nnew MyJsonDeserializationSchema(), consumerConfig));\n\n\nWhile I push the json event to the Kinesis stream intermittently I see this NPE and flink\njob fails\n\n\n2017-04-14 00:31:54,672 WARN  org.apache.flink.streaming.connectors.kinesis.FlinkKinesisConsumer\n - Error while closing Kinesis data fetcher\n\njava.lang.NullPointerException\n\n               at org.apache.flink.streaming.connectors.kinesis.internals.KinesisDataFetcher.shutdownFetcher(KinesisDataFetcher.java:472)\n\n               at org.apache.flink.streaming.connectors.kinesis.FlinkKinesisConsumer.cancel(FlinkKinesisConsumer.java:246)\n\n               at org.apache.flink.streaming.connectors.kinesis.FlinkKinesisConsumer.close(FlinkKinesisConsumer.java:256)\n\n               at org.apache.flink.api.common.functions.util.FunctionUtils.closeFunction(FunctionUtils.java:43)\n\n               at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.dispose(AbstractUdfStreamOperator.java:127)\n\n               at org.apache.flink.streaming.runtime.tasks.StreamTask.disposeAllOperators(StreamTask.java:442)\n\n               at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:343)\n\n               at org.apache.flink.runtime.taskmanager.Task.run(Task.java:655)\n\n               at java.lang.Thread.run(Thread.java:745)\n\nThanks\nSathi\n\n\n\n",
      "type": "Body",
      "meta": null
    },
    {
      "id": 8,
      "start": 17003,
      "end": 17065,
      "text": "\nHi Ted, Sorry for my big font earlier\u00e2\u20ac\u00a6was not intended \u00e2\u02dc\u00ba\n",
      "type": "Body/Intro",
      "meta": null
    },
    {
      "id": 9,
      "start": 16616,
      "end": 17003,
      "text": "From: Sathi Chowdhury <Sathi.Chowdhury@elliemae.com<mailto:Sathi.Chowdhury@elliemae.com>>\nDate: Thursday, April 13, 2017 at 5:44 PM\nTo: Ted Yu <yuzhihong@gmail.com<mailto:yuzhihong@gmail.com>>\n\nCc: \"user@flink.apache.org<mailto:user@flink.apache.org>\" <user@flink.apache.org<mailto:user@flink.apache.org>>\nSubject: Re: Flink errors out and job fails--IOException from CollectSink.open()\n",
      "type": "Header",
      "meta": null
    },
    {
      "id": 10,
      "start": 12728,
      "end": 16616,
      "text": "The taskmanger log does not point a line in my code ..but it seems like the error occurs while\nit is trying to fetch kinesis record inside connector jar\n\nred sequence number 49572261908151269541343187919820576263466496304458235906\n2017-04-13 23:28:23,470 INFO  org.apache.flink.streaming.connectors.kinesis.FlinkKinesisConsumer\n - Subtask 0 is seeding the fetcher with restored shard KinesisStreamShard{streamName='dev-ingest-kinesis-us-west-2',\nshard='{ShardId: shardId-000000000009,HashKeyRange: {StartingHashKey: 306254130228844617117037146688591390310,EndingHashKey:\n340282366920938463463374607431768211455},SequenceNumberRange: {StartingSequenceNumber: 49572254078827945986407789245674345090539511066904232082,}}'},\nstarting state set to the restored sequence number LATEST_SEQUENCE_NUM\n2017-04-13 23:28:23,471 WARN  org.apache.flink.streaming.connectors.kinesis.FlinkKinesisConsumer\n - Error while closing Kinesis data fetcher\njava.lang.NullPointerException\n        at org.apache.flink.streaming.connectors.kinesis.internals.KinesisDataFetcher.shutdownFetcher(KinesisDataFetcher.java:472)\n        at org.apache.flink.streaming.connectors.kinesis.FlinkKinesisConsumer.cancel(FlinkKinesisConsumer.java:246)\n        at org.apache.flink.streaming.connectors.kinesis.FlinkKinesisConsumer.close(FlinkKinesisConsumer.java:256)\n        at org.apache.flink.api.common.functions.util.FunctionUtils.closeFunction(FunctionUtils.java:43)\n        at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.dispose(AbstractUdfStreamOperator.java:127)\n        at org.apache.flink.streaming.runtime.tasks.StreamTask.disposeAllOperators(StreamTask.java:442)\n        at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:343)\n        at org.apache.flink.runtime.taskmanager.Task.run(Task.java:655)\n        at java.lang.Thread.run(Thread.java:745)\n2017-04-13 23:28:23,471 WARN  org.apache.flink.streaming.connectors.kinesis.FlinkKinesisConsumer\n - Error while closing Kinesis data fetcher\njava.lang.NullPointerException\n        at org.apache.flink.streaming.connectors.kinesis.internals.KinesisDataFetcher.shutdownFetcher(KinesisDataFetcher.java:472)\n        at org.apache.flink.streaming.connectors.kinesis.FlinkKinesisConsumer.cancel(FlinkKinesisConsumer.java:246)\n        at org.apache.flink.streaming.connectors.kinesis.FlinkKinesisConsumer.close(FlinkKinesisConsumer.java:256)\n        at org.apache.flink.api.common.functions.util.FunctionUtils.closeFunction(FunctionUtils.java:43)\n        at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.dispose(AbstractUdfStreamOperator.java:127)\n        at org.apache.flink.streaming.runtime.tasks.StreamTask.disposeAllOperators(StreamTask.java:442)\n        at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:343)\n        at org.apache.flink.runtime.taskmanager.Task.run(Task.java:655)\n        at java.lang.Thread.run(Thread.java:745)\n2017-04-13 23:28:23,472 INFO  org.apache.flink.runtime.taskmanager.Task                  \n  - Source: Custom Source (1/1) (8a7301a437cb2d052208ee42c994104b) switched from CANCELING\nto CANCELED.\n2017-04-13 23:28:23,471 INFO  org.apache.flink.streaming.connectors.kinesis.FlinkKinesisConsumer\n - Subtask 0 is seeding the fetcher with restored shard KinesisStreamShard{streamName='dev-ingest-kinesis-us-west-2',\nshard='{ShardId: shardId-000000000006,HashKeyRange: {StartingHashKey: 204169420152563078078024764459060926873,EndingHashKey:\n238197656844656924424362225202237748018},SequenceNumberRange: {StartingSequenceNumber: 49572254078761043750812197376249737935721565982386290786,}}'},\nstarting state set to the restored sequence number LATEST_SEQUENCE_NUM\n2017-04-13 23:28:23,472 INFO  org.apache.flink.runtime.taskmanager.Task                  \n  - Freeing task resources for Source: Custom Source (1/1) (8a7301a437cb2d052208ee42c994104b).\n\n\n",
      "type": "Body",
      "meta": null
    },
    {
      "id": 11,
      "start": 12604,
      "end": 12728,
      "text": "On Thu, Apr 13, 2017 at 5:46 PM, Sathi Chowdhury <Sathi.Chowdhury@elliemae.com<mailto:Sathi.Chowdhury@elliemae.com>>\nwrote:\n",
      "type": "Header",
      "meta": null
    },
    {
      "id": 12,
      "start": 12289,
      "end": 12604,
      "text": "\nHere is the line where NPE was thrown:\n\n    mainThread.interrupt(); // the main thread may be sleeping for the discovery interval\n\nI wonder if runFetcher() encountered running being false - otherwise mainThread should not\nhave been null.\n\nLooks like we should check whether mainThread is null when shutting down.\n\n",
      "type": "Body",
      "meta": null
    },
    {
      "id": 13,
      "start": 11903,
      "end": 12289,
      "text": "From: Ted Yu <yuzhihong@gmail.com<mailto:yuzhihong@gmail.com>>\nDate: Thursday, April 13, 2017 at 6:01 PM\nTo: Sathi Chowdhury <Sathi.Chowdhury@elliemae.com<mailto:Sathi.Chowdhury@elliemae.com>>\nCc: \"user@flink.apache.org<mailto:user@flink.apache.org>\" <user@flink.apache.org<mailto:user@flink.apache.org>>\nSubject: Re: Flink errors out and job fails--IOException from CollectSink.open()\n",
      "type": "Header",
      "meta": null
    },
    {
      "id": 14,
      "start": 4308,
      "end": 11903,
      "text": "\nIn my jobmanager log I see this exception , probably is the root cause why the whole job is\nkilled\u00e2\u20ac\u00a6is there any memory problem in jobmanager ? any clue for this error below?\nI ran the yarn-session\n\n\nAnd my flink-conf.yaml is pretty much unmodified\njobmanager.heap.mb: 256\n\ntaskmanager.heap.mb: 512\n\ntaskmanager.numberOfTaskSlots: 2\n\ntaskmanager.memory.preallocate: false\n\nparallelism.default: 1\n\ninvoke of yarn-session.sh\nHADOOP_CONF_DIR=/etc/hadoop/conf $FLINK_HOME/bin/yarn-session.sh -d -n 2 -s 1 -tm 2048\n\nThanks\nThe error in job manager is as below\n\n2017-04-14 04:26:33,570 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph     \n  - Co-Flat Map -> Sink: Unnamed (1/1) (0c515e082713970381dcd34da87cfcf4) switched from\nRUNNING to FAILED.\njava.lang.RuntimeException: Could not forward element to next operator\n        at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:425)\n        at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:407)\n        at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:797)\n        at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:775)\n        at org.apache.flink.streaming.api.operators.TimestampedCollector.collect(TimestampedCollector.java:51)\n        at com.elliemae.stream.StreamerImpl$StreamerCoFlatMapFunction.flatMap2(StreamerImpl.java:253)\n        at com.elliemae.stream.StreamerImpl$StreamerCoFlatMapFunction.flatMap2(StreamerImpl.java:234)\n        at org.apache.flink.streaming.api.operators.co.CoStreamFlatMap.processElement2(CoStreamFlatMap.java:56)\n        at org.apache.flink.streaming.runtime.io.StreamTwoInputProcessor.processInput(StreamTwoInputProcessor.java:213)\n        at org.apache.flink.streaming.runtime.tasks.TwoInputStreamTask.run(TwoInputStreamTask.java:87)\n        at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:272)\n        at org.apache.flink.runtime.taskmanager.Task.run(Task.java:655)\n        at java.lang.Thread.run(Thread.java:745)\nCaused by: java.io.IOException: Error sending data back to client (ip-172-31-31-172/172.31.31.172:46147)\n        at org.apache.flink.contrib.streaming.CollectSink.invoke(CollectSink.java:64)\n        at org.apache.flink.streaming.api.operators.StreamSink.processElement(StreamSink.java:38)\n        at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:422)\n        ... 12 more\nCaused by: com.esotericsoftware.kryo.KryoException: java.net.SocketException: Connection reset\n        at com.esotericsoftware.kryo.io.Output.flush(Output.java:165)\n        at com.esotericsoftware.kryo.io.Output.require(Output.java:142)\n        at com.esotericsoftware.kryo.io.Output.writeString_slow(Output.java:444)\n        at com.esotericsoftware.kryo.io.Output.writeString(Output.java:345)\n        at com.esotericsoftware.kryo.serializers.DefaultSerializers$StringSerializer.write(DefaultSerializers.java:173)\n        at com.esotericsoftware.kryo.serializers.DefaultSerializers$StringSerializer.write(DefaultSerializers.java:166)\n        at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:599)\n        at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:95)\n        at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:21)\n        at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:599)\n        at org.apache.flink.api.java.typeutils.runtime.kryo.KryoSerializer.serialize(KryoSerializer.java:203)\n        at org.apache.flink.contrib.streaming.CollectSink.invoke(CollectSink.java:61)\n        ... 14 more\nCaused by: java.net.SocketException: Connection reset\n        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:115)\n        at java.net.SocketOutputStream.write(SocketOutputStream.java:155)\n        at java.io.DataOutputStream.write(DataOutputStream.java:107)\n        at org.apache.flink.api.java.typeutils.runtime.DataOutputViewStream.write(DataOutputViewStream.java:39)\n        at com.esotericsoftware.kryo.io.Output.flush(Output.java:163)\n        ... 25 more\n2017-04-14 04:26:33,572 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph     \n  - Job Flink Streaming Job (6c9267453a74d0ef58e678351ac0b49c) switched from state RUNNING\nto FAILING.\n2017-04-14 04:49:10,707 WARN  akka.remote.ReliableDeliverySupervisor                     \n  - Association with remote system [akka.tcp://flink@ip-172-31-31-172.us-west-2.compute.internal:37737]\nhas failed, address is now gated for [5000] ms. Reason: [Association failed with [akka.tcp://flink@ip-172-31-31-172.us-west-2.compute.internal:37737]]\nCaused by: [Connection refused: ip-172-31-31-172.us<http://ip-172-31-31-172.us>-west-2.compute.internal/172.31.31.172:37737]\n2017-04-14 04:49:10,712 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph     \n  - Source: Custom Source (1/1) (b9af6dd459e576a669a12b08a830c24e) switched from DEPLOYING\nto RUNNING.\n2017-04-14 04:49:10,713 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph     \n  - Source: Custom Source (1/1) (c5fe4b6df26e03f4c2604ec89a92ad8f) switched from DEPLOYING\nto RUNNING.\n2017-04-14 04:49:10,715 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph     \n  - Source: Custom Source (1/1) (7f614d51527252cbb9ffcfc0d660fe4e) switched from DEPLOYING\nto RUNNING.\n2017-04-14 04:49:10,717 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph     \n  - Co-Flat Map (1/1) (cd1f1ecf9408b4ac58bea6be99e5c89a) switched from DEPLOYING to RUNNING.\n2017-04-14 04:49:10,718 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph     \n  - Co-Flat Map -> Sink: Unnamed (1/1) (82713fda323b6325815b1b228a3d93f8) switched from\nDEPLOYING to RUNNING.\n2017-04-14 04:49:10,740 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph     \n  - Co-Flat Map -> Sink: Unnamed (1/1) (82713fda323b6325815b1b228a3d93f8) switched from\nRUNNING to FAILED.\njava.io.IOException: Cannot connect to the client to send back the stream\n        at org.apache.flink.contrib.streaming.CollectSink.open(CollectSink.java:80)\n        at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:36)\n        at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:112)\n        at org.apache.flink.streaming.runtime.tasks.StreamTask.openAllOperators(StreamTask.java:386)\n        at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:262)\n        at org.apache.flink.runtime.taskmanager.Task.run(Task.java:655)\n        at java.lang.Thread.run(Thread.java:745)\nCaused by: java.net.ConnectException: Connection refused (Connection refused)\n        at java.net.PlainSocketImpl.socketConnect(Native Method)\n        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)\n        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)\n        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)\n        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)\n        at java.net.Socket.connect(Socket.java:589)\n        at java.net.Socket.connect(Socket.java:538)\n        at java.net.Socket.<init>(Socket.java:434)\n        at java.net.Socket.<init>(Socket.java:244)\n        at org.apache.flink.contrib.streaming.CollectSink.open(CollectSink.java:75)\n        ... 6 more\n\n\n",
      "type": "Body",
      "meta": null
    },
    {
      "id": 15,
      "start": 4820,
      "end": 4828,
      "text": "\nThanks\n",
      "type": "Body/Outro",
      "meta": null
    },
    {
      "id": 16,
      "start": 3925,
      "end": 4308,
      "text": "From: Sathi Chowdhury <Sathi.Chowdhury@elliemae.com<mailto:Sathi.Chowdhury@elliemae.com>>\nDate: Thursday, April 13, 2017 at 9:52 PM\nTo: Ted Yu <yuzhihong@gmail.com<mailto:yuzhihong@gmail.com>>, \"user@flink.apache.org<mailto:user@flink.apache.org>\"\n<user@flink.apache.org<mailto:user@flink.apache.org>>\nSubject: Re: Flink errors out and job fails--IOException from CollectSink.open()\n",
      "type": "Header",
      "meta": null
    },
    {
      "id": 17,
      "start": 3916,
      "end": 3923,
      "text": "Thanks\n",
      "type": "Body/Outro",
      "meta": null
    },
    {
      "id": 18,
      "start": 3424,
      "end": 3925,
      "text": "\nI am consistently seeing the same behavior\u00e2\u20ac\u00a6tried with elevated memory for job manager and\ntaskmanager\ntaskmanager.rpc.port: 6123\ntaskmanager.data.port: 4964\ntaskmanager.heap.mb: 39000\ntaskmanager.numberOfTaskSlots: 1\ntaskmanager.network.numberOfBuffers: 16368\ntaskmanager.memory.preallocate: false\nparallelization.degree.default: 4\neven though the jobmanager is  restarting the flink job ,but the subtasks once reach to cancelled\nstate does not revive\nI have no clue how to approach this.\nThanks\n\n\n",
      "type": "Body",
      "meta": null
    },
    {
      "id": 19,
      "start": 3101,
      "end": 3424,
      "text": "From: Sathi Chowdhury <Sathi.Chowdhury@elliemae.com<mailto:Sathi.Chowdhury@elliemae.com>>\nDate: Friday, April 14, 2017 at 1:29 AM\nTo: \"user@flink.apache.org<mailto:user@flink.apache.org>\" <user@flink.apache.org<mailto:user@flink.apache.org>>\nSubject: Re: Flink errors out and job fails--IOException from CollectSink.open()\n",
      "type": "Header",
      "meta": null
    },
    {
      "id": 20,
      "start": 3092,
      "end": 3099,
      "text": "Thanks\n",
      "type": "Body/Outro",
      "meta": null
    },
    {
      "id": 21,
      "start": 358,
      "end": 3101,
      "text": "\nI have redone the pipeline with flink-1.3-SNAPSHOT and running on EMR 5.4, the aws-sdk-java\nlatest libraries directly in flink lib dir.\nI have come to the point where I get the java.net.SocketException: Broken pipe (Write failed).\nEager to get a reply and a clue on this!\n\njava.io.IOException: Error sending data back to client (ip-172-31-42-238/172.31.42.238:42753)\n        at org.apache.flink.contrib.streaming.CollectSink.invoke(CollectSink.java:64)\n        at org.apache.flink.streaming.api.operators.StreamSink.processElement(StreamSink.java:38)\n        at org.apache.flink.streaming.runtime.io.StreamInputProcessor.processInput(StreamInputProcessor.java:208)\n        at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask.run(OneInputStreamTask.java:66)\n        at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:261)\n        at org.apache.flink.runtime.taskmanager.Task.run(Task.java:679)\n        at java.lang.Thread.run(Thread.java:745)\nCaused by: com.esotericsoftware.kryo.KryoException: java.net.SocketException: Broken pipe\n(Write failed)\n        at com.esotericsoftware.kryo.io.Output.flush(Output.java:165)\n        at com.esotericsoftware.kryo.io.Output.require(Output.java:142)\n        at com.esotericsoftware.kryo.io.Output.writeString_slow(Output.java:444)\n        at com.esotericsoftware.kryo.io.Output.writeString(Output.java:345)\n        at com.esotericsoftware.kryo.serializers.DefaultSerializers$StringSerializer.write(DefaultSerializers.java:173)\n        at com.esotericsoftware.kryo.serializers.DefaultSerializers$StringSerializer.write(DefaultSerializers.java:166)\n        at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:599)\n        at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:95)\n        at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:21)\n        at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:599)\n        at org.apache.flink.api.java.typeutils.runtime.kryo.KryoSerializer.serialize(KryoSerializer.java:202)\n        at org.apache.flink.contrib.streaming.CollectSink.invoke(CollectSink.java:61)\n        ... 6 more\nCaused by: java.net.SocketException: Broken pipe (Write failed)\n        at java.net.SocketOutputStream.socketWrite0(Native Method)\n        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)\n        at java.net.SocketOutputStream.write(SocketOutputStream.java:155)\n        at java.io.DataOutputStream.write(DataOutputStream.java:107)\n        at org.apache.flink.api.java.typeutils.runtime.DataOutputViewStream.write(DataOutputViewStream.java:41)\n        at com.esotericsoftware.kryo.io.Output.flush(Output.java:163)\n        ... 17 more\nThanks\n\n\n",
      "type": "Body",
      "meta": null
    }
  ],
  "meta": {},
  "id": "eval/train_1808"
}